<a href="https://colab.research.google.com/github/parijat-purohit/all_my_codes/blob/main/playground.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import torch
import numpy as np


tensor_1 = torch.tensor([1,2,3,4])
tensor_2 = torch.tensor([5,6,7,8])

In [26]:
# Addition
torch.add(tensor_1, tensor_2)

tensor([ 6,  8, 10, 12])

In [28]:
# Substraction
torch.sub(tensor_2, tensor_1)

tensor([4, 4, 4, 4])

In [30]:
# Multiplication
torch.mul(tensor_1, tensor_2)

tensor([ 5, 12, 21, 32])

In [31]:
# Division
torch.div(tensor_2, tensor_1)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [33]:
# Remainder
torch.remainder(tensor_2, tensor_1)

tensor([0, 0, 1, 0])

In [35]:
# Assignment
tensor_1.add_(tensor_2)
tensor_1

tensor([ 6,  8, 10, 12])